[package]
name = "whisper-rs-test"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"
log4rs = { version = "1.3.0", features = ["console_appender"] }
serde_json = "1.0.128"
#voice_activity_detector = "0.1.1"
ort = { version = "2.0.0-rc.6", features = ["ndarray"] }
ndarray = "0.16"
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", version = "0.13.0", features = ["metal","whisper-cpp-log"] }
