url = "https://www.am1430.net/wp-content/uploads/show/%E7%B9%BC%E7%BA%8C%E6%9C%89%E5%BF%83%E4%BA%BA/2023/2024-10-03.mp3"
#database_file_path = "./tmp/example.db"
vad_onnx_model_path="./models/silero_vad.onnx"
whisper_model_path="/Users/it3/codes/andrew/transcribe_audio/whisper_models/ggml-large-v3-turbo.bin"
language="yue"
operation = "transcribe" # or save_to_file